FROM node:16 as builder
WORKDIR /usr/src/app
COPY package.json ./
RUN yarn
COPY ./ ./
RUN pwd
RUN yarn build

FROM nginx
EXPOSE 5173
COPY ./nginx/static/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html